<head>
    <title>conditions d'utilisation </title>
</head>

<style>
    .terms_of_use{
        width: 70%;
        margin: 0 auto;
    }

    .terms_of_use h1, .terms_of_use h2{
        color: #183e67;
    }
    
    .terms_of_use h2{
        text-decoration: underline;
    }
    
    .terms_of_use p{
        color: dimgray;
        font-family: sans-serif, courier;
    }

</style>

<body>
    
    <?php include 'div_panier.php'; ?>
    
    <div>
        <?php include 'navbar.php'; ?>
    </div>
    
    <div class="terms_of_use">
    
        <h1>Terms and conditions of use.</h1>
        <p>The terms and conditions of use, which are likely to be changed in a punctual way, apply to all our services, available directly or indirectly (by means of our partners) online, by e-mail or by telephone. By achieving our website or any other website platform (indicated together by " the website "), by performing researches there, by using them and/or by performing a reservation there, you declare that you have acquainted yourself with the present general terms of use and our privacy policy , you have understood their range and have accepted them.<br />
        These pages, their contents and (their) facilities, as well as the booking service of accommodations and online activities which are provided  on these pages and through this website (the "Service ") belong in, are managed and are provided by ESCAPADEFRANCAISE.COM,  ESCAPADE FRANCAISE ("EscapadeFrancaise.com", "us", "our" or "our"). They are only put at your disposal for a non commercial and personal use which remains subjected to the terms and conditions of use established below.</p>
    
        <h2>I. Range of our service</h2>
        <p>By means of this website, we (ESCAPADEFRANCAISE.COM EF.COM EFCOM  ESCAPADE FRANCAISE and its partners (of distribution) affiliated) give an online portal thanks to all types of  accommodations (for example, guests' rooms, indicated together by "accommodations (s) ") and activities providers can offer their rooms and activities services. Thank to that , the users of the Internet site can perform a reservation in these same establishments and contractors. By making a reservation through EscapadeFrancaise.com, you get involved in a direct contractual relationship with the establishment concerned by your reservation. As soon as you perform a reservation, we act only as intermediary between you and the establishment and/or contractor, by transmitting them the details of your reservation and by sending you an e-mail of confirmation for and in their name.<br />
        During the benefit of our services, the information we announce are based on the information given to us by the establishments and contractors of activities. Establishments and contractors have therefore the access to a mail contact, by means of which they held the whole responsibility to update all their prices, available funds and other information shown on our website. We do our best to provide you a quality service, we can prove and guarantee accuracy, precision or exhaustiveness of information. However, we cannot be held responsible for any error (obvious error or typographical error), any complete failure (due to a technical fault, temporary and/or partial, breakdown, repair, update, improvement or service of our website or other ), any vague, misleading or wrong information, or any lack of information. Every establishment and contractor are responsible at any time for the definite, complete and precise character of the (descriptive) information which concern them and which are on our website, including their rates and available funds.<br />
        Our services are only available for a non-commercial and private use. You cannot therefore sell retail, use, copy, watch (for example, by means of an indexation robot or screen shots), to show, to download, to reproduce or to establish deep links towards any content ,information, software, product or available services on our website as part of an activity or a commercial or competitive objective.</p>
 
        <h2>II. Prices, crossed-out rates and best price guarantee</h2>
        <p>The prices offered on our website are very competitive. All prices and rates shown on the website EscapadeFrancaise.com are pointed out by room and by activity for the duration of stay. They include VAT and all other taxes (subjected to modification), except opposite mention on our website or on the confirmation email of reservation. The applicable taxes will be able to be invoiced by the establishment in case of no-show or of cancellation fee.<br />
        Lower rates are sometimes available on our website for some dates in an establishment and/or given contractor. However, these lower rates offered by establishments can be subjected to conditions and specific restrictions, notably as regards the conditions of cancellation and refund. Please consult carefully descriptions of rooms, activities and rates to acquaint yourself with such conditions before booking your stay.<br />
        Obvious errors (including typographical errors) are not executable. All special offers and promotions are pointed out as such.</p>

        <h2>III. Confidentiality of information and cookies</h2>
        <p>EscapadeFrancaise.com respects your personal data.</p>

        <h2>IV. A free service</h2>
        <p>Our service is free. Contrary to many societies, we will not invoice you our service and we will not add any freshly additional fee (of reservation) to the accommodation rate.<br />
        Guesthouses and contractors of activities pay a commission (corresponding to a percentage of the accommodation price ) which is transferred to  EscapadeFrancaise.com ,once the client stays (and pays) the Guesthouses and/or benefits from the services of our activity contractor.</p>
        
        <h2>V. Bank card and banking transfer</h2>
        <p>Our payment procedure is entirely secure. When you pay with your credit/debit card or your bank account , your money is safely transferred to our bank account . Then we transfer it to the partner establishment/ contractor via a third payment processor.<br />
        For some non refundable rates and special offers, please note that the establishment has the right to ask for a prepayment by bank transfer or by credit card ,and therefore your credit card may be pre-authorised or charged (sometimes without any option for refund) upon making the reservation. Before performing your reservation, please read carefully the description of the rooms to acquaint yourself with such conditions.<br />
        In case of a fraudulent or a non-authorized use of your payment card or by a third person, most banks and credit card companies cover the risk and take all the expenses resulting from aforementioned fraud or a non-authorized use, net of a possible deductible (generally fixed to 50 EUROS or the same amount in your local currency). If your bank or credit card society invoices this deductible after a non-authorized transaction resulting from a reservation made on our website, we pay you back the aforementioned deductible with a maximum amount of 50 EUROS (or the equivalent in your local currency). In order to undertake your indemnity, be sure that you informed your bank or credit card society of this fraud or non-authorized use (in accordance with their regulations and procedures of information) and please contact us immediately by e-mail. (info@escapadefrancaise.com). Thank you for indicating «fraudulent use of a bank card» in the subject of your e-mail and to give us a proof of deductible (for example a copy of the banking establishment policy). This indemnity applies only to reservations by credit card performed on the secured server  by EscapadeFrancaise.com, and if an unauthorised use of your credit card does not result from an error from your part during the use of the aforementioned secured server.</p>
        
        <h2>VI. Cancellation and no-show</h2>
        <p>By performing a reservation in an establishment, you accept and agree the conditions of cancellation and of no-show of the establishment, as well as all additional conditions of aforementioned establishment that may apply to your reservation or during your stay, including for services rendered and/or products offered by the establishment (the sales conditions of an establishment can be obtained to the relevant establishment).The general cancellation and no-show policy of each Supplier is made available on our Platform on the Supplier information pages, during the reservation procedure and in the confirmation email or ticket (if applicable).<br />
        Please note that some rates or special offers can not be cancelled or changed.  Applicable tourism taxes can be taken by the accommodation in case of no-show or charged cancellation. You are therefore invited to acquaint yourself with conditions of every accommodation before booking your reservation.<br />
        Please note that a reservation which requires down payment or (complete or partial) prepayment may be cancelled (without a prior notice of default or warning) insofar the relevant (remaining) amount(s) cannot be collected in full on the relevant payment date in accordance with the relevant payment policy of the establishment and the reservation.<br />
        You will be held responsible for any delay of payment, debit or credit card details, invalid credit/debit cards or insufficient funds are for your own risk and account and you shall not be entitled to any refund of any (non-refundable) prepaid amount unless the establishment agrees or allows otherwise under its (pre)payment and cancellation policy.<br />
        If you want to check, to change or to cancel your reservation, please refer to the confirmation email and follow the instructions which are pointed out there. Please note that any cancellation can be charged, in accordance with the conditions of cancellation, of pre-payment and no show policy of the establishments and that pre-paid amounts are not refundable. We advise you to read carefully these conditions of cancellation, of pre- payment and of no-show before performing your reservation and to make further payments on time as may be required for the relevant reservation.<br />
        In case of late arrival on the check-in day or of arrival on the following day, make sure to inform the establishment as soon as possible so they know when to expect you to avoid cancellation of your reservation or room or invoice of the no-show fee. Our customer service can help you to contact the relevant establishment. However, EscapadeFrancaise.com can not be held responsible for the consequences of your late arrival or every cancellation or no-show fee realise by the establishment.</p>
 

        <h2>VII. (Further) Correspondence and communications</h2>
        <p>By performing a reservation, you agree to receive (i) an e-mail which we will be able to send you before your date of arrival in the establishment, that will contain information of your destination and pertinent offer for your stay.<br />
        EscapadeFrancaise.com excludes any responsibility during communications with the establishment on or via its platform. You cannot derive any rights from any request to, or communication with the establishment or (any form of) acknowledgement of receipt of any communication or request. EscapadeFrancaise.com cannot guarantee that any request or communication will be (duly and timely) received/read by, complied with, executed or accepted by the establishment.<br />
        To finalise and to guarantee your reservation in the correct way, you are required to use a valid email address. We exclude any responsibility (and we are not required to verify) any wrong email address, telephone number or invalid credit card number.</p>
        
        <h2>VIII. Limitation of liability</h2>
        <p>In accordance with the limitations set out in these terms and conditions and to the extent permitted by law, we could only be held responsible for direct damages actually suffered, paid or incurred by you due to an attributable shortcoming of our obligations in respect to our services, up to an aggregate amount of the aggregate cost of your reservation as set out in the confirmation email (whether for one event or series of linked events).<br />
        However and to the extent permitted by law, neither we nor any of our officers, directors, employees, representatives, subsidiaries, affiliated companies, distributors, affiliate (distribution) partners, licensees, agents or others involved in creating, sponsoring, promoting, or otherwise making available the site and its contents shall be liable for (1) any punitive, special, indirect or consequential loss or damages, any loss of production, loss of profit, loss of revenue, loss of contract, loss of or damage to goodwill or reputation, loss of claim, (2) any inaccuracy relating to the (descriptive) information (including rates, availability and ratings) of the establishment as made available on our Platform, (3) the services rendered or the products offered by the establishment or other business partners, (4) any (direct, indirect, consequential or punitive) damages, losses or costs suffered, incurred or paid by you, pursuant to, arising out of or in connection with the use, inability to use or delay of our Platform, or (5) any (personal) injury, death, property damage, or other (direct, indirect, special, consequential or punitive) damages, losses or costs suffered, incurred or paid by you, whether due to (legal) acts, errors, breaches, (gross) negligence, willful misconduct, omissions, non-performance, misrepresentations, tort or strict liability by or (wholly or partly) attributable to the establishment or any of our other business partners (including any of their employees, directors, officers, agents, representatives or affiliated companies) whose products or service are (directly or indirectly) made available, offered or promoted on or through the Platform, including any (partial) cancellation, overbooking, strike, force majeure or any other event beyond our will.<br />
        Whether or not the establishment where you stay invoices you your accommodation , or if we are facilitating the payment of the (room/reservation) price, you agree and acknowledge that the establishment is at all times responsible for the collection, withholding, remittance and payment of the applicable taxes due on the total amount of the (room/reservation) price to the relevant tax authorities. EscapadeFrancaise.com is not liable or responsible for the remittance, collection, withholding or payment of the relevant taxes due on the (room/reservation) price to the relevant tax authorities.<br />
        By downloading photos / pictures in our system (for example by sending a comment), you certify and guarantee to have the copyright of the photos / pictures and you accept that EscapadeFrancaise.com uses these photos / pictures, download on its website (mobile), applis and promotional (online and offline) publications and as EscapadeFrancaise.com at its discretion sees fit.<br />
        You are granting EscapadeFrancaise.com a non-exclusive, worldwide, irrevocable, unconditional, perpetual right and license to use, reproduce, display, have reproduced, distribute, sublicense, communicate and make available the photos/images as EscapadeFrancaise.com  at its discretion sees fit. By uploading these photos/images the person uploading the picture(s) accepts full legal and moral responsibility of any and all legal claims that are made by any third parties (including, but not limited to, accommodation owners) due to EscapadeFrancaise.com  publishing and using these photos/images.<br />
        EscapadeFrancaise.com  does not own or endorse the photos/images that are uploaded. The truthfulness, validity and right to use of all photos/images is assumed by the person who uploaded the photo, and is not the responsibility of EscapadeFrancaise.com . EscapadeFrancaise.com disclaims all responsibility and liability for the pictures posted. The person who uploaded the photo warrants that the photos/images shall not contain any viruses, Trojan horses or infected files and shall not contain any pornographic, illegal, obscene, insulting, objectionable or inappropriate material and does not infringe any third party (intellectual property right, copyright or privacy) rights. Any photo/image that does not meet the aforesaid criteria will not be posted and/or can be removed/deleted by EscapadeFrancaise.com at any time and without prior notice.</p>
        
        <h2>IX.  Ownership and rights of intellectual property</h2>
        <p>Except opposite mention, the necessary software for our services or put in disposition on our website and used by this last, as well as rights of intellectual property (including royalties) of contents, information and equipments of our website, are the exclusive property of ESCAPADEFRANCAISE.COM EF.COM ESCAPADE FRANCAISE, of its suppliers or its contractors.<br />
        EscapadeFrancaise.com remains the only owner of all rights, titles and interests (relating to all rights of intellectual property) of the website (the presentation and the facilities included) on which service is available (clients reviews and translations included). As a result, you are not allowed to copy, to create links (hyper or deep) towards our contents, to publish, to promote, to commercialise, to include or to use our contents in any another way ( translations and clients review included) or our mark without our definite written permission.<br />
        As much as you would use (wholly or partly) or combine our (translated) content (including clients reviews) or would otherwise own any intellectual property rights in the Platform or any (translated) content or guest reviews, you hereby assign, transfer and set over all such intellectual property rights to  EscapadeFrancaise.com  . Any unlawful use or any of the aforementioned actions or behaviour will constitute a material infringement of our intellectual property rights (including copyright and database right).</p>
        
        <h2>X. Miscellaneous</h2>
        <p>To the extent permitted by law, these terms and conditions and the provision of our services shall be governed by and construed in accordance with French law and any dispute arising out of these general terms and conditions and our services shall exclusively be submitted to the competent courts in Paris, France.<br />
        The original French version of these terms and conditions may have been translated into other languages. The translated version is a courtesy and office translation only and you cannot derive any rights from the translated version. In the event of a dispute about the contents or interpretation of these terms and conditions or inconsistency or discrepancy between the French version and any other language version of these terms and conditions, the French language version to the extent permitted by law shall apply, prevail and be conclusive. The French version is available on our Platform (by selecting the French language) or shall be sent to you upon your written request.<br />
        If any provision of these terms and conditions is or becomes invalid, unenforceable or non-binding, you shall remain bound by all other provisions hereof. In such event, such invalid provision shall nonetheless be enforced to the fullest extent permitted by applicable law, and you will at least agree to accept a similar effect as the invalid, unenforceable or non-binding provision, given the contents and purpose of these terms and conditions.</p>
        
        <h2>XI. Regarding EscapadeFrancaise.com and its local offices</h2>
        <p>The service of reservation of guest houses and online activities is rendered by ESCAPADEFRANCAISE.COM EF.COM ESCAPADE FRANCAISE.<br />
        An auto-entrepreneur society recorded in France and its offices are located in France at 67, street Saint-Jacques 75005 Paris. This society is registered at the Chamber of commerce and of the Industry of Paris under the registration number siret 812 039 105 00026.The support companies do not have any Platform.<br />
        EscapadeFrancaise.com has its seat in Paris, in France. The Local Office does not have any website or platform  (and do not in any way control, manage, maintain or host the Platform) and does not have any power and authority to render the service, to represent EscapadeFrancaise.com or to enter into any contractual relation in the name of, for or on behalf of EsapadeFrancaise.com. You do not have a (legal or contractual) relationship with the Local Office.<br />
        This Local office does not operate and is not authorised to act as any form of process or service agent of EscapadeFrancaise.com.  EscapadeFrancaise.com  does not accept nor assume any domicile at any place, location or office in the world (nor in the local office), than the head office in Paris.</p>
   
    </div>
    <?php include 'footer.php'; ?>
</body>